#!/bin/bash

# Image Setup Script for Alfred Paul Portfolio
# This script helps convert HEIC images to web-friendly formats

echo "🖼️  Setting up portfolio images..."

# Create images directory if it doesn't exist
mkdir -p public/images

echo "📱 HEIC Image Conversion Instructions:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Since you have HEIC files (IMG_5415.HEIC and IMG_5799.HEIC), you need to convert them:"
echo ""
echo "Option 1 - Using Mac Preview (Recommended):"
echo "1. Double-click IMG_5415.HEIC to open in Preview"
echo "2. Go to File → Export As..."
echo "3. Choose Format: JPEG"
echo "4. Set Quality to 80-90%"
echo "5. Save as: alfred-paul-profile.jpg"
echo "6. Repeat for IMG_5799.HEIC and save as: alfred-paul-about.jpg"
echo ""
echo "Option 2 - Using online converter:"
echo "1. Visit: https://convertio.co/heic-jpg/"
echo "2. Upload your HEIC files"
echo "3. Download the converted JPG files"
echo ""
echo "Option 3 - Using Terminal (if you have ImageMagick):"
echo "brew install imagemagick"
echo "magick IMG_5415.HEIC alfred-paul-profile.jpg"
echo "magick IMG_5799.HEIC alfred-paul-about.jpg"
echo ""
echo "📁 File Placement:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Place the converted images in:"
echo "• apps/web/public/images/alfred-paul-profile.jpg  (for Hero section)"
echo "• apps/web/public/images/alfred-paul-about.jpg    (for About section)"
echo ""
echo "🎨 Image Recommendations:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Hero Image (alfred-paul-profile.jpg):"
echo "• Should be a professional headshot/portrait"
echo "• Square aspect ratio (1:1) works best"
echo "• Recommended size: 800x800px minimum"
echo "• Subject should be centered"
echo ""
echo "About Image (alfred-paul-about.jpg):"
echo "• Can be a more casual professional photo"
echo "• Portrait or landscape orientation"
echo "• Recommended size: 600x600px minimum"
echo "• Shows you in a working/professional environment"
echo ""
echo "✨ Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Convert your HEIC images to JPG format"
echo "2. Rename them as specified above"
echo "3. Place them in: apps/web/public/images/"
echo "4. Refresh your browser to see the images"
echo ""
echo "The components are already updated to use these images! 🚀"
